2019-03-19T11:29:15.223Z [right now!] error: uncaughtException: Cannot find module 'username-generator'
Error: Cannot find module 'username-generator'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/routes/agencys.js:6:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) Error: Cannot find module 'username-generator'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/routes/agencys.js:6:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2019-03-19T13:12:52.081Z [right now!] error: uncaughtException: Identifier 'validate' has already been declared
/home/pipo/Documents/autoecole/auto-ecole_backend/routes/document.js:2
const {Monitor, validate} = require('../model/monitor');
                ^

SyntaxError: Identifier 'validate' has already been declared
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:13:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17) /home/pipo/Documents/autoecole/auto-ecole_backend/routes/document.js:2
const {Monitor, validate} = require('../model/monitor');
                ^

SyntaxError: Identifier 'validate' has already been declared
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:13:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
2019-03-19T13:13:31.876Z [right now!] error: uncaughtException: await is only valid in async function
/home/pipo/Documents/autoecole/auto-ecole_backend/routes/document.js:17
    const user = await Client.findOne({_id: req.params.id, agency: req.body.agency});
                 ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:13:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17) /home/pipo/Documents/autoecole/auto-ecole_backend/routes/document.js:17
    const user = await Client.findOne({_id: req.params.id, agency: req.body.agency});
                 ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:13:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
2019-03-19T13:14:47.705Z [right now!] error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:217:7)
    at module.exports (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:30:9)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:8:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:217:7)
    at module.exports (/home/pipo/Documents/autoecole/auto-ecole_backend/startup/routes.js:30:9)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:8:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
2019-03-19T14:09:46.890Z [right now!] error: uncaughtException: listen EADDRINUSE :::3000
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
2019-03-19T14:10:01.866Z [right now!] error: uncaughtException: listen EADDRINUSE :::3000
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
2019-03-19T14:11:12.778Z [right now!] error: uncaughtException: listen EADDRINUSE :::3000
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pipo/Documents/autoecole/auto-ecole_backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pipo/Documents/autoecole/auto-ecole_backend/app.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
